variable "image_id" {}
variable "instance_type" {}
variable "key_pair" {}
variable "project" {}
variable "security_group_id" {}
variable "min_size" {}
variable "max_size" {}
variable "desired_capacity" {}
variable "subnet_ids" {}
variable "azs" {}